#!/bin/bash

tcpdump -i any -n 'udp port 53' -l 2>/dev/null | while read line; do
	ip="$(echo "$line" | sed -nE 's/^.* ([0-9]+(\.[0-9]+){3}) \([0-9]+\)$/\1/p')"
	test -z "$ip" && continue
	echo $line
	ipset add whitelisted_ips "$ip" 2>&1 | grep -v "it's already added"
done

