#!/bin/bash
PING_WAIT=10
INTERVAL=20
NUM_ATTEMPTS=3
TARGET=10.9.0.1

count=0
while true; do
	ping -c1 -W${PING_WAIT:-4} $TARGET >/dev/null 2>&1 && count=0 || count=$((count + 1))
	test $count -ge ${NUM_ATTEMPTS:-3} && systemctl restart httptun-launch && count=0
	sleep ${INTERVAL:-60}
done
