#!/bin/bash
CONFIG_PATH="/etc/oisetup"
UUID_PATH="$CONFIG_PATH/uuid.installed"
MAC_PATH="$CONFIG_PATH/oiproctor_mac.installed"

function is_invalid_mac() {
	mac="$1"
	test -z "$mac" -o "$mac" = "ffffffffffff" -o "$mac" = "FFFFFFFFFFFF" -o "$mac" = "000000000000" && return 0
	echo "$mac" | grep -viqe '^[0-9a-f][02468ace][0-9a-f]{10}$' && return 0 # Second hex digit must be even on unicast mac addresses
	return 1
}

base_uuid="$(cat "$UUID_PATH" 2>/dev/null)"
vm_uuid="$(get_vm_uuid)"
mac="$(cat "$MAC_PATH" 2>/dev/null)"
test "$vm_uuid" != "$base_uuid" && mac=""
while is_invalid_mac "$mac"; do
	mac="$(head -c 6 /dev/random | hexdump -v -e '/1 "%02x"')"
done
echo "$mac" > "$MAC_PATH"
echo "$vm_uuid" > "$UUID_PATH"
