#!/bin/bash

export DISPLAY=":0"
IFACE="tap0"
INTERVAL="5"
NOTIFY_TIMEOUT="5"
DISK_FS="ext4"
DISK_LIMIT="95"
TARGET="10.9.0.1"
OSD_FORCE_REFRESH=60
CONFIG_PATH="/etc/oisetup"
OIPROCTOR_MAC_PATH="/etc/oisetup/oiproctor-mac.installed"
TUNNEL_CACHE_PATH="/tmp/tap0cache"

function screen_size {
	export XAUTHORITY=/home/contestant/.Xauthority
	sudo xrandr -d :0 2>/dev/null | grep '*' | uniq | awk '{print $1}'
}

function get_mounted_media {
	df -h --output="target,source,fstype,size,pcent" -a -x tmpfs -x sysfs -x devpts -x cgroup2 -x securityfs -x pstore -x bpf -x proc -x mqueue -x tracefs -x hugetlbfs -x debugfs -x fusectl -x binfmt_misc -x configfs -x devtmpfs | grep -vE '^(/|/proc/sys/fs/binfmt_misc) ' | tail -n +2
}

function disk_space {
	df -t ext4 --output=pcent,avail,target -h | sed -e 1d -e 's/^\s\+//' -e 's/\s\+/ /g'
}

function get_user {
	loginctl list-sessions --no-pager --no-legend | awk '/seat0/{print $3}' | sort | uniq | head -1
}

function get_contest_user {
	sudo get-cms-user
}

function get_message {
	ip="$(ip addr show "$IFACE" 2>/dev/null | awk '/inet / {print $2}' | cut -f1 -d'/')"
	mac_etc="$(cat "$OIPROCTOR_MAC_PATH")"
	if test -n "$ip"; then
		mac_tunnel="$(cat "$TUNNEL_CACHE_PATH" 2>/dev/null | head -c6 | hexdump -v -e '/1 "%02x"')"
		ip_suffix="$(echo "$ip" | cut -d. -f3-)"
		test "$mac_etc" != "$mac_tunnel" && echo -n "$mac_etc <> "
		echo "$mac_tunnel $ip_suffix"
	else
		echo "$mac_etc"
	fi
}

function osd {
	user="$1"
	message="$2"
	if test "${user//-*}" = "guest"; then
		export XAUTHORITY="/home/contestant/.Xauthority"
	else
		unset XAUTHORITY
	fi
	echo "$message" | sudo -u "$user" osd_cat -p top -A center -c grey -d $(($OSD_FORCE_REFRESH + ${INTERVAL:-5})) >/dev/null 2>&1 &
	echo $!
	test "$user" = "lightdm" && sudo -u lightdm /bin/sh -c 'xdotool windowfocus $(xdotool search --name "lightdm-gtk-greeter" | head -1)'
}

last_user=
last_message=
last_pid=
last_timestamp=
old_disk_space=
old_mounted_media="$(get_mounted_media)"
old_screen_size="$(screen_size)"

while true; do
	new_message="$(get_message)"
	new_user="$(get_user)"
	new_contest_user="$(get_contest_user)"
	new_screen_size="$(screen_size)"
	new_mounted_media="$(get_mounted_media)"
	new_timestamp="$(date +%s)"
	if test "$new_message" != "$last_message" || test -n "$last_pid" -a ! -d /proc/"${last_pid:-0}" || test -n "$new_user" -a "$new_user" != "$last_user" || test $(($new_timestamp - $OSD_FORCE_REFRESH)) -gt ${last_timestamp:-0}; then
		test -n "$last_pid" && killall -9 osd_cat 2>/dev/null
		last_pid="$(osd "$new_user" "$new_message")"
		last_user="$new_user"
		last_message="$new_message"
		last_timestamp="$new_timestamp"
	fi
	if test "$old_mounted_media" != "$new_mounted_media"; then
		wget -T "${NOTIFY_TIMEOUT:-5}" -O /dev/null "http://$TARGET/notify?msg=$new_mounted_media $(uptime | cut -d, -f1)"
		old_screen_size="$new_screen_size"
	fi
	if test "$new_screen_size" != "$old_screen_size"; then
		wget -T "${NOTIFY_TIMEOUT:-5}" -O /dev/null "http://$TARGET/notify?msg=$old_screen_size > $new_screen_size $(uptime | cut -d, -f1)"
		old_screen_size="$new_screen_size"
	fi
	new_disk_space="$(disk_space)"
	if test "$new_disk_space" != "$old_disk_space"; then
		IFS=$'\n'
		for line in $(disk_space); do
			test "$(echo "$line" | cut -d% -f1)" -gt "$DISK_LIMIT" && wget -T "${NOTIFY_TIMEOUT:-5}" -O /dev/null "http://$TARGET/notify?msg=$line"
		done
		old_disk_space="$new_disk_space"
	fi
	if test -n "$new_contest_user"; then
		contest_id="$(cat "$CONFIG_PATH/cms_contest_id.installed")"
		wget -T "${NOTIFY_TIMEOUT:-5}" -O /dev/null "http://$TARGET/update?${contest_id}_login=$new_contest_user"
	fi
	sleep ${INTERVAL:-5}
done
