#!/bin/bash

export DISPLAY=:0
IFACE="tap0"
INTERVAL="5"

last_user=
last_message=
last_pid=

function get_user {
	users="$(loginctl list-sessions --no-pager --no-legend | awk '/seat0/{print $3}' | sort | uniq)"
	for user in $users; do
		echo " " | sudo -u "$user" osd_cat -p top -A center -c grey -d 1 && echo $user && break
	done
}

function get_message {
	ip="$(ip addr show "$IFACE" 2>/dev/null | awk '/inet / {print $2}' | cut -f1 -d'/')"
	if test -n "$ip"; then
    		echo "$ip" | cut -d. -f3-
	else
    		mac="$(cat /var/run/randommac)"
    		echo "$mac"
	fi
}

function osd {
	user="$1"
	message="$2"
	echo "$message" | sudo -u "$user" osd_cat -p top -A center -c grey -d 999999999999 >/dev/null2>&1 &
	echo $!
	test "$user" = "lightdm" && sudo -u lightdm /bin/sh -c 'xdotool windowfocus $(xdotool search --name "lightdm-gtk-greeter" | head -1)'
}

while true; do
	new_message="$(get_message)"
	new_user="$(get_user)"
	if test "$new_message" != "$last_message" || test -n "$last_pid" -a ! -d /proc/"${last_pid:-0}" || test -n "$new_user" -a "$new_user" != "$last_user"; then
		#test -n "$last_pid" && kill -9 "$last_pid" 2>/dev/null
		test -n "$last_pid" && killall -9 osd_cat 2>/dev/null
		last_pid="$(osd "$new_user" "$new_message")"
		last_user="$new_user"
		last_message="$new_message"
	fi
	sleep ${INTERVAL:-5}
done
