#!/bin/bash

# Setup
DEFAULT_PROCTOR_USERNAME="oi"
DEFAULT_CUSTOM_LINE_COMMENT="oi-vm"

# Functions (copied from oisetup)
function error {
        echo -e "$@" >&2
        exit 1
}

function remove_custom_lines {

        path="$1"
        always_create="$2"

        if test -f "$path"; then
                grep -v "$CUSTOM_LINE_COMMENT" "$path" > "$path.tmp" && mv -f "$path.tmp" "$path"
        else
                test -n "$always_create" && touch "$path"
        fi

}

# Global variables
TIMEZONE="$1"
PROCTOR_USERNAME="${2:-$DEFAULT_PROCTOR_USERNAME}"
CUSTOM_LINE_COMMENT="${3:-$DEFAULT_CUSTOM_LINE_COMMENT}"

# Context checks
test "$EUID" -ne 0 && error "This script must be run as root!"

# Commandline checks
test $# -lt 1 -o $# -gt 3 && error "Usage: $(basename "$0") <timezone> [proctor_username] [custom_line_comment]"

# Update the system
apt update -y
apt upgrade -y

# Timezone
test -n "$TIMEZONE" && timedatectl set-timezone "$TIMEZONE"

# Keep log small
remove_custom_lines /etc/systemd/journald.conf
echo "SystemMaxUse=100M # $CUSTOM_LINE_COMMENT" >> /etc/systemd/journald.conf
systemctl restart systemd-journald

# Disable os update norifications
remove_custom_lines /etc/update-manager/release-upgrades
echo "Prompt=never # $CUSTOM_LINE_COMMENT" >> /etc/update-manager/release-upgrades
grep -q Hidden=true /etc/xdg/autostart/update-notifier.desktop 2>/dev/null || (touch /etc/xdg/autostart/update-notifier.desktop && echo "Hidden=true" >> /etc/xdg/autostart/update-notifier.desktop)

# Remove shutdown menu
mkdir -p /etc/guest-session/skel/.config/xfce4/xfconf/xfce-perchannel-xml/
cat > /etc/guest-session/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfce4-session" version="1.0">
  <property name="shutdown" type="empty">
    <property name="ShowSwitchUser" type="bool" value="false"/>
    <property name="ShowHibernate" type="bool" value="false"/>
    <property name="ShowSuspend" type="bool" value="false"/>
    <property name="ShowHybridSleep" type="bool" value="false"/>
  </property>
</channel>
EOF
mkdir -p /etc/xdg/xfce4/kiosk
cat > /etc/xdg/xfce4/kiosk/kioskrc << EOF
[xfce4-session]
SaveSession=NONE
EOF

# Create oi user
if ! id "$PROCTOR_USERNAME" >/dev/null 2>&1; then
	oi_user_pwd="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)"
	useradd -m "$PROCTOR_USERNAME" && echo "$PROCTOR_USERNAME:$oi_user_pwd" | chpasswd && echo "ATTENTION: Created new user oi with password: $oi_user_pwd"
	oi_user_pwd="" # Clear password from memmory
fi

# Allow SSH connections into oi user
apt install -y ssh
remove_custom_lines /etc/ssh/ssh_config.d/oi.conf true
cat >> /etc/ssh/ssh_config.d/oi.conf << EOF
PermitRootLogin no # $CUSTOM_LINE_COMMENT
UseDNS no # $CUSTOM_LINE_COMMENT
PasswordAuthentication no # $CUSTOM_LINE_COMMENT
ChallengeResponseAuthentication no # $CUSTOM_LINE_COMMENT
AllowUsers $PROCTOR_USERNAME # $CUSTOM_LINE_COMMENT
EOF
systemctl restart sshd
test ! -d "/home/$PROCTOR_USERNAME/.ssh" && mkdir "/home/$PROCTOR_USERNAME/.ssh" && chown "$PROCTOR_USERNAME" "/home/$PROCTOR_USERNAME/.ssh"
! test -f "/home/$PROCTOR_USERNAME/.ssh/authorized_keys" && touch "/home/$PROCTOR_USERNAME/.ssh/authorized_keys"
grep -qvE '^[[:space:]]*(ssh|ecdsa)-' "/home/$PROCTOR_USERNAME/.ssh/authorized_keys" && echo "Attention: Add in /home/$PROCTOR_USERNAME/.ssh ssh-rsa generated by the proctor"
sudo chown oi:oi -R "/home/$PROCTOR_USERNAME/.ssh"
sudo chmod go-rwx -R "/home/$PROCTOR_USERNAME/.ssh"

# Guest user startup scripts
remove_custom_lines /etc/guest-session/prefs.sh true
echo "ln -sf $HOME /home/contestant # $CUSTOM_LINE_COMMENT" >> /etc/guest-session/prefs.sh
echo "adduser $USER guests # $CUSTOM_LINE_COMMENT" >> /etc/guest-session/prefs.sh

# Boot into guest user (all settings are lost at logoff)
echo "[Seat:*]\nallow-guest=true\nautologin-guest=true" > /etc/lightdm/lightdm.conf.d/40-enable-guest.conf
echo "[Seat:*]\ngreeter-setup-script=/usr/local/sbin/lock_message.sh" > /etc/lightdm/lightdm.conf.d/40-enable-lock-message.conf.disable

# Guest user init
test ! -d /etc/guest-session/skel/ && mkdir /etc/guest-session/skel/

# Enlarge processes stack and recursivity to equalize that of CMS evaluations
cat > /etc/security/limits.d/30-stack.conf << EOF
hard stack 262144
soft stack 262144
EOF
remove_custom_lines /etc/guest-session/skel/.profile true
echo "ulimit -s 262144 # $CUSTOM_LINE_COMMENT" >> /etc/guest-session/skel/.profile

#s Install Firefox compatible with guest user. Ubuntu now ships firefox as a Snap, so we need to install it as a deb in order to prepopulate its configuration for the guest user
apt autopurge -y chromium-browser
snap remove chromium
snap remove firefox
apt autopurge -y snapd
add-apt-repository -y ppa:mozillateam/ppa
cat > /etc/apt/preferences.d/mozilla-firefox << EOF
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
EOF
echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' > /etc/apt/apt.conf.d/51unattended-upgrades-firefox
apt update
apt install -y firefox
/usr/bin/xdg-settings set default-web-browser firefox.desktop
# Disable AppArmor so firefox works correctly in guest session
sed -i 's/^GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="apparmor=0"/' /etc/default/grub
update-grub

# Install (de)compression tool integrated with file namanger
apt install -y thunar-archive-plugin

# Install development tools
sudo apt install -y build-essential clang vim idle default-jdk g++ geany

# Default to C++17
rm -f /bin/g++ /usr/bin/g++
echo -r '#!/bin/bash\nexec /bin/g++-11 -std=c++17 "$@"' > /bin/g++
chmod a+rx /bin/g++
ln -f /bin/g++ /usr/bin/g++ 2>/dev/null # Not symbolic link, hard link

# Install Sublime text
apt install -y wget
wget -qO- https://download.sublimetext.com/sublimehq-pub.gpg > /etc/apt/keyrings/sublimehq-pub.asc
echo -e 'Types: deb\nURIs: https://download.sublimetext.com/\nSuites: apt/stable/\nSigned-By: /etc/apt/keyrings/sublimehq-pub.asc' > /etc/apt/sources.list.d/sublime-text.sources
apt update
apt install -y sublime-text

# Install VSCode
apt install -y gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor --batch --yes -o /usr/share/keyrings/microsoft.gpg
echo -e "Types: deb\nURIs: https://packages.microsoft.com/repos/code\nSuites: stable\nComponents: main\nArchitectures: amd64,arm64,armhf\nSigned-By: /usr/share/keyrings/microsoft.gpg" > /etc/apt/sources.list.d/vscode.sources
apt update
apt install -y code
mkdir -p /etc/guest-session/skel/.local/share/applications
cat > /etc/guest-session/skel/.local/share/applications/code.desktop << EOF
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --no-sandbox %F
Icon=vscode
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=TextEditor;Development;IDE;
MimeType=application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;
[Desktop Action new-empty-window]
Name=New Empty Window
Name[de]=Neues leeres Fenster
Name[es]=Nueva ventana vacía
Name[fr]=Nouvelle fenêtre vide
Name[it]=Nuova finestra vuota
Name[ja]=新しい空のウィンドウ
Name[ko]=새 빈 창
Name[ru]=Новое пустое окно
Name[zh_CN]=新建空窗口
Name[zh_TW]=開新空視窗
Exec=/usr/share/code/code --no-sandbox --new-window %F
Icon=vscode
EOF
code --install-extension ms-vscode.cpptools
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
cp -r ~/.vscode /etc/guest-session/skel/.vscode
rm -f /etc/guest-session/skel/.vscode/argv.json

# Remove unnecessary applications
apt autopurge -y libreoffice-* thunderbird transmission-* xfburn pidgin

# Disable keyrings prompts
apt autopurge -y gnome-keyring seahorse

# Clean up
sudo apt autoremove -y --purge
sudo apt clean -y